### ISSUE TITLE
Delete role (404)

### ISSUE THREAD

**Issue by ninjaparade** [orchestral/control#32]
### Steps to reproduce this.

- Create a new role.
- Once you return index (table view) click delete.

returns `NotFoundHttpException`

**Comment by ninjaparade** [comment]
That resolved the 404 error, but I think now due to the resource routes and the `DELETE` route requires a form and a _token rather than just a button with the `GET`.
https://github.com/orchestral/control/blob/master/src/Http/Controllers/RolesController.php#L30

**Comment by crynobone** [comment]
Fixes missing `_token` via 3165d7f
